defaults:
  parallelism: 10
phases:
  - name: builtins
    count: 5
    builtins: [COUNT, SUM, AVG, MIN, MAX, COALESCE, NULLIF, CONCAT, LENGTH, SUBSTRING, LOWER, UPPER, TRIM, REPLACE, EXTRACT, DATE_TRUNC, NOW, CURRENT_DATE, CURRENT_TIMESTAMP, AGE, TO_CHAR, ROUND, CEIL, FLOOR, MOD, ABS, ROW_NUMBER, RANK, LAG, LEAD]
    prompt_template: builtin_sql_template.txt
    use_sample_rows: true
    dataset_output_file_dir: generated_datasets/builtins

  - name: schema_docs
    count: 100
    parallelism: 10
    prompt_template: schema_doc_template.txt
    use_sample_rows: false
    dataset_output_file_dir: generated_datasets/schema_docs


  - name: single_table
    count: 5
    use_sample_rows: true
    prompt_template: single_table_sql_template.txt
    dataset_output_file_dir: generated_datasets/single_table

  - name: joins
    count: 25
    examples_file: fewshot/multi_table_examples.yaml
    use_sample_rows: false
    dataset_output_file_dir: generated_datasets/joins

  - name: sample_data
    n_rows: 2
    use_sample_rows: true
    dataset_output_file_dir: generated_datasets/sample_data

  - name: schema_relationship
    count: 100
    n_rows: 500
    prompt_template: schema_relationship_template.txt
    dataset_output_file_dir: generated_datasets/schema_relationship

budget_usd: 10.0
openai_model: gpt-4.1
