defaults:
  parallelism: 10
  tag_schema_json: true
  db_cocurrent_session: 50
phases:
  - name: builtins
    count: 25
    builtins: [COUNT, SUM, AVG, MIN, MAX, COALESCE, NULLIF, CONCAT, LENGTH, SUBSTRING, LOWER, UPPER, TRIM, REPLACE, EXTRACT, DATE_TRUNC, NOW, CURRENT_DATE, CURRENT_TIMESTAMP, AGE, TO_CHAR, ROUND, CEIL, FLOOR, MOD, ABS, ROW_NUMBER, RANK, LAG, LEAD]
    prompt_template: builtin_sql_template.txt
    use_sample_rows: true
    dataset_output_file_dir: generated_datasets/builtins
    tag_schema_json: false

  - name: schema_docs
    count: 800
    parallelism: 16
    api_answer_count: 100
    prompt_template: schema_doc_template.txt
    use_sample_rows: false
    dataset_output_file_dir: generated_datasets/schema_docs
    tag_schema_json: false
    enable_worker_chat_log: false


  - name: single_table
    count: 500
    parallelism: 50
    use_sample_rows: true
    prompt_template: single_table_sql_template.txt
    dataset_output_file_dir: generated_datasets/single_table
    tag_schema_json: false
    api_answer_count: 50

  - name: joins
    count: 180
    parallelism: 40
    api_answer_count: 60
    use_sample_rows: true
    min_joins: 2
    dataset_output_file_dir: generated_datasets/joins
    tag_schema_json: false

  - name: complex_sqls
    count: 30
    use_sample_rows: true
    parallelism: 50
    min_joins: 3
    dataset_output_file_dir: generated_datasets/complex_sqls
    tag_schema_json: false

  - name: sample_data
    n_rows: 2
    use_sample_rows: true
    dataset_output_file_dir: generated_datasets/sample_data
    tag_schema_json: true

  - name: schema_relationship
    count: 100
    n_rows: 500
    prompt_template: schema_relationship_template.txt
    dataset_output_file_dir: generated_datasets/schema_relationship
    tag_schema_json: false

budget_usd: 50.0
openai_model: gpt-4.1
